### ISSUE TITLE
国产自主研发的木兰语言源码已更新

### ISSUE THREAD

**Issue by Ayx03** [tucaoba2333/monyhar-lite-MultiLang-kernel#22]
[Pull request #21](https://github.com/tucaoba2333/monyhar-lite-MultiLang-kernel/pull/21)
merge [OpenCatBrowser](https://github.com/AtomOpen/OpenCatBrowser) from [AtomOpen Foundation](https://github.com/AtomOpen)

**Comment by Lunar-525** [comment]
阅

**Comment by Lunar-525** [comment]
阅
